remove simpli-web-sdk
simplitech/simplicli-webusecase pull request #1
Opened 2020-03-25 17:46 UTC by melanke

2020-03-25 17:47 UTC, melanke commented on package.json
> +    "@vue/cli-service": "^4.2.3",
talvez seja isso q esteja atrapalhando o commit

2020-03-25 17:48 UTC, melanke commented on src/config/framework.config.ts
> +import * as moment from 'moment'
I would like to refactor this file, any suggestion will be very much appreciated

2020-03-25 17:57 UTC, melanke commented on package.json
> +    "@vue/cli-service": "^4.2.3",
but my second commit didn't require to bypass, so let's just forget about it for now

2020-03-28 21:22 UTC, melanke commented
@ftgibran please review my last commit

2020-03-29 19:23 UTC, ftgibran requested changes

2020-03-29 19:23 UTC, ftgibran commented on package.json
> -    "lodash": "^4.17.11",
Why did you remove lodash? We are using it.

2020-03-29 19:23 UTC, ftgibran commented on package.json
>      "tailwindcss-grid": "^1.2.1",
I think tailwindcss-grid should be in devDependencies

2020-03-29 19:23 UTC, ftgibran commented on postcss.config.js
>      './node_modules/pretty-checkbox/**/*.scss',
You have forgotten to include sweetalert2 in the whitelist postcss

2020-03-29 19:23 UTC, ftgibran commented on src/config/HttpConfig.ts
> + * This configuration will be set in @/bootstrap/app.ts
Could you fix this commentary replacing @/bootstrap/app.ts to @/app/Setup? There are other similar files too.

2020-03-29 19:23 UTC, ftgibran commented on src/config/HttpConfig.ts
> +        config.headers['Accept-Language'] = App.language
I have forgotten to replace App and Auth to $.app and $.auth in this section. Could you do it for me in order to avoid imports?

2020-03-29 19:23 UTC, ftgibran commented on src/app/Setup.ts
> +    RequestListener.onRequestEnd(reqName => $.await.done(reqName))
I created a issue to implement onRequestError event. This event should be here in order to use $.await.error. This is very important.

2020-03-30 17:48 UTC, melanke commented on package.json
> -    "lodash": "^4.17.11",
usecase dont need it, so if the project needs it you can manually add

2020-03-30 19:45 UTC, merged

2020-03-30 19:58 UTC, melanke commented
🤘